-- AlterTable
ALTER TABLE "articles" ADD COLUMN     "content" TEXT,
ADD COLUMN     "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "negative" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "neutral" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "positive" INTEGER NOT NULL DEFAULT 0;
